services:
  # --- BASE DE DATOS SQL (PostgreSQL) ---
  postgres_db:
    image: postgres:15-alpine
    container_name: tdah_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: tdah_gamification_db
    ports:
      - "5432:5432" # Puerto estándar de Postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - tdah_network

  # --- VISOR GRÁFICO PARA POSTGRES (pgAdmin) ---
  pgadmin:
    image: dpage/pgadmin4
    container_name: tdah_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80" # Entrarás por http://localhost:5050
    depends_on:
      - postgres_db
    networks:
      - tdah_network

  # --- BASE DE DATOS NOSQL (MongoDB) ---
  mongo_db:
    image: mongo:6.0
    container_name: tdah_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
    ports:
      # CAMBIO IMPORTANTE: 
      # El primer número es tu PC (27018), el segundo es el contenedor (27017).
      # Esto evita el conflicto con tu Mongo local.
      - "27018:27017" 
    volumes:
      - mongo_data:/data/db
    networks:
      - tdah_network

volumes:
  postgres_data:
  mongo_data:

networks:
  tdah_network:
    driver: bridge