services:
  # Base de Datos ÃšNICA (MongoDB)
  mongo_db:
    image: mongo:6.0
    container_name: tdah_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
    ports:
      - "27018:27017" # Puerto externo 27018
    volumes:
      - mongo_data:/data/db
    networks:
      - tdah_network

volumes:
  mongo_data:

networks:
  tdah_network:
    driver: bridge